### ISSUE TITLE
CUBLAS_STATUS_ALLOC_FAILED & Is it possible to change the working GPU ?

### ISSUE THREAD

**Issue by JulianStiebler** [hacksider/Deep-Live-Cam#696]
**Describe the bug**
No idea. Preview works totally fine, even scrubbing frame by frame. Older versions (~1month) work fine aswell. Newest version since UI rework doesnt work at all, using either possible inswapper-models.

```
2024-10-04 22:12:41.7561938 [E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] 
Non-zero status code returned while running Gemm node. 
Name:'fc1' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 
onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall 
CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=DESKTOP-BMSSD90 ; 
file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; 
line=168 ; expr=cublasCreate(&cublas_handle_);
```

I feel like it seems like a memory allocation issue when creating videos in the newest versions for whatever reason. Also, GPU=0 means for me my internal Laptop GPU, while GPU 1 is my nVidia graphics card, though it always has worked but that maybe the reason why it's so slow.. 

**Is there maybe also a way to change the target GPU like in my case to 1?** Though as mentioned older versions of this tool worked totally fine.

![grafik](https://github.com/user-attachments/assets/dbec63e7-c5ce-4bab-9953-577f99381b27)

**To Reproduce**
- Creating a video in any way on newest versions

**Expected behavior**
- Working video generation

**Desktop (please complete the following information):**
 - OS: Windows 10, 
 - Cuda Toolkit 11.8 
 - onnxruntime-gpu==1.16.3

**Comment by JulianStiebler** [comment]
It turned out to be a driver problems for me actually if someone stumbles upon this.
Installing CUDA has overwritten my driver and installed a apparently incompatible one. Reinstalling the current driver version fixed it.

**Comment by shagratt** [comment]
Got the same issue. Old versions works fine. So i changed this file with a one from an older version:
Deep-Live-Cam-main\modules\processors\frame\face_swapper.py
and now it works 100% of the time. So need to find what is done in a different way in this file.
